export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QUANTITY = "ADJUST_QUANTITY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const LOAD_TMDB_MOVIES = "LOAD_TMDB_MOVIES";
export const LOAD_TMDB_MOVIES_SUCCESS = "LOAD_TMDB_MOVIES_SUCCESS";
